import "./globals.css";
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const themes = {
    light: "public/light.css",
    dark: "public/dark.css",
  };
  return (
    <html lang="en">
      <body>
        {/* <ThemeSwitcherProvider defaultTheme="light" themeMap={themes}> */}
        <Header />
        <div>{children}</div>
        <Footer />
        {/* </ThemeSwitcherProvider> */}
      </body>
    </html>
  );
}
